name: rst_flutter
description: "锐石 RSTONE - Flutter多平台应用"
publish_to: 'none'

version: 0.0.188+29609850

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_markdown: ^0.6.18
  yaml: ^3.1.2
  path_provider: ^2.1.2
  pdf: ^3.11.3
  printing: ^5.14.2
  shared_preferences: ^2.2.2
  reorderables: ^0.6.0
  share_plus: ^10.0.0
  package_info_plus: ^8.0.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/产品列表/
    - assets/产品应用/
    - assets/产品配方/
    - assets/产品TDS/
    - assets/产品列表.json
    - assets/产品应用.json
    - assets/产品配方.json
    - assets/产品TDS.json
    - assets/fonts/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon: false
